### ISSUE TITLE
Lat/Long location data

### ISSUE THREAD

**Issue by cbjrobertson** [haccer/twint#140] opened 2018-06-04 13:12 UTC
I'd like to work on latitude and longitude location data into the `twint` outputs, in addition to nearest city, which is what it is apparently doing now. However, I don't want to duplicate your efforts if this is something you've already tried to do. Have @haccer or any other people working on the package, looked into doing this?

**Comment by pielco11** [comment] 2018-06-04 13:37
Really interesting but I do not enough time to work on it, if you would like to help us that could be really useful

I did not talk with Cody about this, and so I'm not sure if he is working on it... anyway feel free to write code here or (better) create a PR (to dev)

**Comment by cbjrobertson** [comment] 2018-06-04 13:43
Ok, cool:) I'll look into it.

**Comment by haccer** [comment] 2018-06-04 21:18
It seems Tweets don't display location info on them [anymore](https://twitter.com/search?f=tweets&vertical=default&q=near%3Alondon)... or maybe I cannot find them.

**Comment by cbjrobertson** [comment] 2018-06-05 14:43
Yeah, I looked through as well and couldn't find anything. It makes sense, for obvious privacy reasons that they wouldn't display such info publicly.

**Comment by aaeissa** [comment] 2018-06-05 17:40
Coordinates used to be available at ['coordinates']['coordinates'] in the Tweet object. The docs still show this (https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html) but I think it's been removed as well. 

I started a project last fall that relied heavily on those coordinates. I just came back to it recently and noticed it was not collecting *any* data. I thought I had something misconfigured.  

Maybe the location info is being stripped because of the recent GDPR compliance deadlines?

**Comment by pielco11** [comment] 2018-06-05 18:18
It seems that Twitter removed the `location` info from the Tweet, but you can still search for Tweets near a place: `near:"Venice, Italy"` ; plus you have an argument `within: 15ml` that auto describe itself. Not a specific geocode but still something

**Comment by cbjrobertson** [comment] 2018-06-05 19:20
The within argument allows fractions of km/ml, as well, so you can get quite precise.

**Comment by pielco11** [comment] 2018-06-05 19:29
Yes, that's right... but the problem is that you will have to specify the location (localtion -> tweet) and you don't have *viceversa* (tweet -> location)

**Comment by cbjrobertson** [comment] 2018-06-05 21:53
Yes, it does seem that way...

Cole

**Comment by haccer** [comment] 2018-06-06 21:07
Yeah, I a while ago i added `--location` to collect the location from a Twitter user's profile because of that.

Going to close this for now. When I get a crazy idea to try and get tweet attached location data i'll do it

**Closed by haccer** 2018-06-06 21:07 UTC
Labels: enhancement

**Comment by Ali-khavanin** [comment] 2019-12-11 11:55
> The within argument allows fractions of km/ml, as well, so you can get quite precise.
> […](#)
> On 5 Jun 2018, at 19:18, Francesco Poldi ***@***.***> wrote: It seems that Twitter removed the location info from the Tweet, but you can still search for Tweets near a place: near:"Venice, Italy" ; plus you have an argument within: 15ml that auto describe itself. Not a specific geocode but still something — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hi there! 
if I may ask, I want to know how can I figure out if a crawled tweet is in a certain area or not?
for example, I'm crawling 100,000 tweets which contains a keyword 
and i want to know which one of those 100,000 tweets are in "35.715298, 51.404343, 15km "
what should I do?

i really appreciate your help
@pielco11 (sorry for being annoying :sweat_smile:  )

**Comment by pielco11** [comment] 2019-12-11 14:21
@Ali-khavanin don't worry

so 100k tweets are a lot, thus this is a hard case. I'd suggest you to split the searches as better as possible. For example you might run different scripts at the same time, but with different since/until, keywords, from/to args, and specifying that geo region as well. The newly crawled tweets will match the region, and the others will not be in it. Basically you have to re-run the query adding the `near` param
