### ISSUE TITLE
SystemExit: 0 Error Date problem

### ISSUE THREAD

**Issue by yonilevine** [haccer/twint#84] opened 2018-05-02 20:39 UTC
### Initial Check 
Make sure you've checked the following.

- [] Python version is 3.5 or higher.
- [] Using the latest version of Twint.

If this is a feature request please specify in the title:

Example:
> [REQUEST] More features!

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.

### Description of Issue
Please use as much detail as possible.

### OS Details
Using Windows, Linux? What OS version?

Hello, love your package!

Running into some problems while searching, it seems to be happening every thirty days or so. Thanks
I'm using Mac OS in a Jupyter Notebook

# Configure
tweet = twint.Config
tweet.Format = " UserID:{user_id} | Username: {username} | Date:{date} | Time:{time} | Tweet: {tweet} | Hashtags:{hashtags} | Replies:{replies} | Likes:{likes} | Retweets:{retweets} | Location:{location} | Timezone:{timezone} "
tweet.To = "attcares"
tweet.Show_hashtags = True
tweet.Store_csv = True
tweet.Until = '2016-10-02'
tweet.Since = '2016-01-01'
tweet.Output = "atttweets2016_4.csv"
# Run
twint.Search(tweet)

The TB is as follows

SystemExit                                Traceback (most recent call last)
<ipython-input-51-3baa75e5256b> in <module>()
      9 tweet.Output = "atttweets2016_3.csv"
     10 # Run
---> 11 twint.Search(tweet)

~/anaconda3/envs/python3/lib/python3.6/site-packages/twint/search.py in __init__(self, config)
     36 
     37                 loop = asyncio.get_event_loop()
---> 38                 loop.run_until_complete(self.main())
     39 
     40         async def Feed(self):

~/anaconda3/envs/python3/lib/python3.6/asyncio/base_events.py in run_until_complete(self, future)
    452         future.add_done_callback(_run_until_complete_cb)
    453         try:
--> 454             self.run_forever()
    455         except:
    456             if new_task and future.done() and not future.cancelled():

~/anaconda3/envs/python3/lib/python3.6/asyncio/base_events.py in run_forever(self)
    419             events._set_running_loop(self)
    420             while True:
--> 421                 self._run_once()
    422                 if self._stopping:
    423                     break

~/anaconda3/envs/python3/lib/python3.6/asyncio/base_events.py in _run_once(self)
   1429                     self._current_handle = None
   1430             else:
-> 1431                 handle._run()
   1432         handle = None  # Needed to break cycles when an exception occurs.
   1433 

~/anaconda3/envs/python3/lib/python3.6/asyncio/events.py in _run(self)
    143     def _run(self):
    144         try:
--> 145             self._callback(*self._args)
    146         except Exception as exc:
    147             cb = _format_callback_source(self._callback, self._args)

~/anaconda3/envs/python3/lib/python3.6/site-packages/twint/search.py in main(self)
     83                                 self.config.Until = str(self.d._until)
     84                                 if len(self.feed) > 0:
---> 85                                         await self.tweets()
     86                                 else:
     87                                         self.d._until = self.d._until - datetime.timedelta(days=int(self.config.Timedelta))

~/anaconda3/envs/python3/lib/python3.6/site-packages/twint/search.py in tweets(self)
     71                                 for tweet in self.feed:
     72                                         self.count += 1
---> 73                                         await output.Tweets(tweet, "", self.config, self.conn)
     74                 else:
     75                         self.initial = 0

~/anaconda3/envs/python3/lib/python3.6/site-packages/twint/output.py in Tweets(tw, location, config, conn)
    157         copyright = tw.find("div", "StreamItemContent--withheld")
    158         if copyright is None:
--> 159                 Tweet = getTweet(tw, location, config)
    160 
    161                 if config.Database:

~/anaconda3/envs/python3/lib/python3.6/site-packages/twint/output.py in getTweet(tw, location, config)
    131                 if (t.date.date() - datetime.datetime.strptime(config.Since, "%Y-%m-%d").date()).days == -1:
    132                 # mitigation here, maybe find something better
--> 133                         sys.exit(0)
    134         t.datestamp = t.date.strftime("%Y-%m-%d")
    135         t.time = getTime(tw)

SystemExit: 0

**Comment by haccer** [comment] 2018-05-03 03:25
Thank you, looking into it right now

**Comment by haccer** [comment] 2018-05-03 04:33
Due to the nature of Twitter's search, sometimes tweets are included a day before the specified `since` date. What was causing the program to exit was a temporary mitigation in place to not include those tweets. 

For now I've [commented those lines out](https://github.com/haccer/twint/commit/b10415e4c645eace1d3b1d78b57dbb83d8c50831), so the it should work as intended.

Going to keep this issue open until I figure out a proper way to mitigate this.

**Comment by pielco11** [comment] 2018-05-03 08:56
As said, that's how Twitter search works... maybe we can add a "date check" after we retrieve tweets and if the date of the tweets is before since/after until we just pass over, twint will retrieve them but will not to write them to stdout/file/database/whatever

I think that this could be a solution (read mitigation)

**Comment by haccer** [comment] 2018-05-03 10:06
Heh, maybe since it seems to always be including the day before, we change the day before it gets passed.

**Comment by haccer** [comment] 2018-05-03 10:16
Testing out a new mitigation technique right now

**Comment by haccer** [comment] 2018-05-03 10:50
This new function works.

```python
def datecheck(datestamp, config):
	d = int(datestamp.replace("-", ""))
	s = int(config.Since.replace("-", ""))
	if d < s:
		sys.exit(1)
```

Your script @yonilevine should work as intended now. Tested & closing issue.

**Closed by haccer** 2018-05-03 10:50 UTC
Labels: Twitter Flaw

**Comment by pielco11** [comment] 2018-06-23 10:27
#164
